### ISSUE TITLE
pyproject.toml (Solution to path issues with imports) 

### ISSUE THREAD

**Issue by SanjinDedic** [SanjinDedic/agent_games#121]
The desired side effect of the .toml packaging is that all the imports have path access to the root directory

Here is how the file structure would look:

```
agent_games/
├── pyproject.toml
├── src/
│   └── agent_games/
│       ├── __init__.py
│       ├── docker/
│       ├── games/
│       ├── parallel_sim/
│       └── various Python files
├── tests/
└── README.md
```

`pyproject.toml` would look something like this 
```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agent_games"
version = "0.1.0"
description = "A framework for running agent-based game competitions"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "sqlmodel",
    "pydantic",
    "httpx",
    # Add all your dependencies here
]

[tool.hatch.build.targets.wheel]
packages = ["src/agent_games"]

[tool.pytest.ini_options]
pythonpath = ["src"]
```

The package would then be installed in development mode:
```bash
pip install -e .
```

Not sure how this would affect deployment to EC2 or if there are any negative effects of this
